version: 0.0.{build}
clone_folder: C:\projects\Mezz_Filesystem

image:
  - Visual Studio 2022

environment:
  matrix:
  - GENERATOR: Visual Studio 17 2022 Win64

configuration:
  - Debug
  - Release

before_build:
  # Finalize build prep
  - mkdir build
  - cd build
  - mkdir JagatiPackages
  - set JAGATI_DIR=C:\projects\Mezz_Filesystem\build\JagatiPackages
  - echo "Current Configuration is '%CONFIGURATION%'"
  - cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% .. -DMEZZ_BuildDoxygen=OFF

build_script:
  - cmake --build . --config %CONFIGURATION%

test_script:
  - cmd: cd C:\projects\Mezz_Filesystem\build
  - cmd: Filesystem_Tester xml

notifications:
- provider: Email
  to:
  - contact@blacktoppstudios.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

